#
# This file is part of Nokia OMAF implementation
#
# Copyright (c) 2018 Nokia Corporation and/or its subsidiary(-ies). All rights reserved.
#
# Contact: omaf@nokia.com
#
# This software, including documentation, is protected by copyright controlled by Nokia Corporation and/ or its
# subsidiaries. All rights are reserved.
#
# Copying, including reproducing, storing, adapting or translating, any or all of this material requires the prior
# written consent of Nokia.
#

os: linux
language: cpp
sudo: true

matrix:
  include:
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_ENV="CC=gcc-7 && CXX=g++-7"
    - env:
        - ANDROID_NDK=/opt/android-ndk-r17c
        - MATRIX_ENV="BUILD_ABI=abiv7 && BUILD_TYPE=debug && LIBDIR=Debug/armeabi-v7a  && PLAYER_LIB=libOMAFPlayerd"
    - env:
        - ANDROID_NDK=/opt/android-ndk-r17c
        - MATRIX_ENV="BUILD_ABI=abiv7 && BUILD_TYPE= && LIBDIR=Release/armeabi-v7a  && PLAYER_LIB=libOMAFPlayer"
    - env:
        - ANDROID_NDK=/opt/android-ndk-r17c
        - MATRIX_ENV="BUILD_ABI=abiv8 && BUILD_TYPE=debug && LIBDIR=Debug/arm64-v8a && PLAYER_LIB=libOMAFPlayerd"
    - env:
        - ANDROID_NDK=/opt/android-ndk-r17c
        - MATRIX_ENV="BUILD_ABI=abiv8 && BUILD_TYPE= && LIBDIR=Release/arm64-v8a && PLAYER_LIB=libOMAFPlayer"

# language environment overrides some of the user env values set in matrix so they are reapplied here
before_install:
  - eval "${MATRIX_ENV}"
  - pushd .
  - if [ ! -z "$ANDROID_NDK" ]; then mkdir -p /opt; fi 
  - if [ ! -z "$ANDROID_NDK" ]; then cd /opt; wget https://dl.google.com/android/repository/android-ndk-r17c-linux-x86_64.zip; fi 
  - if [ ! -z "$ANDROID_NDK" ]; then cd /opt; unzip -q android-ndk-r17c-linux-x86_64.zip; fi
  - popd
  - export
  - cmake --version
  - $CXX --version

install:
  - pushd .
  - cd ..
  - git clone https://github.com/nokia/libdash.git
  - git clone --single-branch -b OMAF https://github.com/nokiatech/heif.git
  - popd
  - pushd .
  - cd OpenGLExt
  - curl -o gl/glext.h https://www.khronos.org/registry/OpenGL/api/GL/glext.h
  - curl -o wgl/wglext.h https://www.khronos.org/registry/OpenGL/api/GL/wglext.h
  - curl -o KHR/khrplatform.h https://www.khronos.org/registry/EGL/api/KHR/khrplatform.h
  - popd

before_script:
  - pushd .
  - cd build
  - '[ -z "$ANDROID_NDK" ] && (
      bash ./build-linux.sh && 
      bash ./build-linux.sh debug
    ) || [ ! -z "$ANDROID_NDK" ]'
  - '[ ! -z "$ANDROID_NDK" ] && (
      bash ./build-android.sh $BUILD_ABI $BUILD_TYPE
    ) || [ -z "$ANDROID_NDK" ]'
  - popd

script:
  - '[ -z "$ANDROID_NDK" ] && ( 
      [ -x Creator/bin/Linux/Debug/omafvi ] && 
      [ -x Creator/bin/Linux/Release/omafvi ] && 
      [ -x Creator/bin/Linux/Debug/omafimage ] && 
      [ -x Creator/bin/Linux/Release/omafimage ] && 
      [ -x Creator/bin/Linux/Debug/omafvd ] && 
      [ -x Creator/bin/Linux/Release/omafvd ] && 
      Creator/bin/Linux/Debug/omafvi --help && 
      Creator/bin/Linux/Debug/omafimage --help && 
      Creator/bin/Linux/Release/omafvi --help &&
      Creator/bin/Linux/Release/omafimage --help 
    ) || [ ! -z "$ANDROID_NDK" ]'
  - '[ ! -z "$ANDROID_NDK" ] && ( 
      [ -f Player/Lib/Android/$LIBDIR/libdash.so ] && 
      [ -f Player/Lib/Android/$LIBDIR/libmp4vr_shared.so ] && 
      [ -f Player/Lib/Android/$LIBDIR/$PLAYER_LIB.so ]
    ) || [ -z "$ANDROID_NDK" ]'

