#
# This file is part of Nokia OMAF implementation
#
# Copyright (c) 2018 Nokia Corporation and/or its subsidiary(-ies). All rights reserved.
#
# Contact: omaf@nokia.com
#
# This software, including documentation, is protected by copyright controlled by Nokia Corporation and/ or its
# subsidiaries. All rights are reserved.
#
# Copying, including reproducing, storing, adapting or translating, any or all of this material requires the prior
# written consent of Nokia.
#

os: linux
language: cpp
sudo: true

matrix:
  include:
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_ENV="CC=gcc-6 && CXX=g++-6"
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - MATRIX_ENV="CC=clang-3.6 && CXX=clang++-3.6"
    - env:
        - PATH=/opt/cmake-3.7.2-Linux-x86_64/bin:$PATH
        - ANDROID_NDK=/opt/android-ndk-r14b
        - MATRIX_ENV=""

# language environment overrides some of the user env values set in matrix so they are reapplied here
before_install:
  - eval $MATRIX_ENV
  - pushd .
  - if [ ! -z "$ANDROID_NDK" ]; then mkdir -p /opt; fi 
  - if [ ! -z "$ANDROID_NDK" ]; then cd /opt; wget https://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip; fi 
  - if [ ! -z "$ANDROID_NDK" ]; then cd /opt; wget https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz; fi
  - if [ ! -z "$ANDROID_NDK" ]; then cd /opt; unzip -q android-ndk-r14b-linux-x86_64.zip; fi
  - if [ ! -z "$ANDROID_NDK" ]; then cd /opt; tar zxf cmake-3.7.2-Linux-x86_64.tar.gz; fi
  - popd
  - export
  - cmake --version
  - $CXX --version

install:
  - pushd .
  - cd ..
  - git clone https://github.com/nokia/libdash.git
  - popd
  - pushd .
  - cd OpenGLExt
  - curl -o gl/glext.h https://www.khronos.org/registry/OpenGL/api/GL/glext.h
  - curl -o wgl/wglext.h https://www.khronos.org/registry/OpenGL/api/GL/wglext.h
  - curl -o KHR/khrplatform.h https://www.khronos.org/registry/EGL/api/KHR/khrplatform.h
  - popd

script:
  - cd build
  - if [ -z "$ANDROID_NDK" ]; then ./build-linux.sh && ./build-linux.sh debug; fi
  - if [ ! -z "$ANDROID_NDK" ]; then ./build-android.sh abiv7 && ./build-android.sh abiv8 && ./build-android.sh abiv7 debug && ./build-android.sh abiv8 debug; fi
